# version: "3"

# Use postgres/example user/password credentials

services:
  # db:
  #   # db app transaction ga dipakai, memakai db di config yaml
  #   image: postgres:15
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: example
  #     POSTGRES_DB: mydb
  #   ports:
  #     - 5433:5432
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  # adminer:
  #   image: adminer
  #   ports:
  #     - 8082:8080

  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092, CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT, CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      # - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    ports:
      - 9092:9092
      - 9093:9093

volumes:
  postgres_data:
